---
title: "A1"
author: "Lillian (Wei) Hung"
date: "9/27/2021"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = F)

#---------------------------------------------------------------------

library(tidyverse)

#---------------------------------------------------------------------

# Electricity Consumption 2017-2020
years <- 2017:2020
quarters <- 1:4
type <- "Electric"

pge_elec <- NULL

# loop for reading files from 2017 Q1 - 2020 Q4 Electricity Data
for(year in years) {
  
  for(quarter in quarters){
  
    filename <- 
      paste0(
        "pge/PGE_",
        year,
        "_Q",
        quarter,
        "_",
        type,
        "UsageByZip.csv"
      )

    print(filename)
  
    temp <- read_csv(filename)
  
  pge_elec <- rbind(pge_elec,temp)
  # Note rbind requires field names to be consistent for every new thing that you add.

  saveRDS(pge_elec, "pge_elec.rds")
  }
}

#---------------------------------------------------------------------

# loop for reading files from 2021 Q1- 2021 Q2 Electricity Data
year <- 2021
quarters <- 1:2
type <- "Electric"

for(quarter in quarters) {
  
  filename <- 
    paste0(
      "pge/PGE_",
      year,
      "_Q",
      quarter,
      "_",
      type,
      "UsageByZip.csv"
    )

  print(filename)
  
  temp <- read_csv(filename)
  
  pge_elec <- rbind(pge_elec,temp)
  # Note rbind requires field names to be consistent for every new thing that you add.

  saveRDS(pge_elec, "pge_elec.rds")
}

#---------------------------------------------------------------------

# filter electricity data with customerclass: residential and commercial
pge_elec_filter <- 
  filter(
    pge_elec,
    CUSTOMERCLASS %in% 
      c(
        "Elec- Residential",
        "Elec- Commercial"
      )
  )

#---------------------------------------------------------------------

# Convertion: kWhs to kBTUs
pge_elec_filter<-within(pge_elec_filter,kBTUs<-TOTALKWH*3.41214)
pge_elec_filter2 <- pge_elec_filter[,-c(7,8)]

#---------------------------------------------------------------------

# Gas Consumption 2017-2020
years <- 2017:2020
quarters <- 1:4
type <- "Gas"

pge_gas <- NULL

for(year in years) {
  
  for(quarter in quarters){
  
    filename <- 
      paste0(
        "pge/PGE_",
        year,
        "_Q",
        quarter,
        "_",
        type,
        "UsageByZip.csv"
      )

    print(filename)
  
    temp <- read_csv(filename)
  
  pge_gas <- rbind(pge_gas,temp)
  # Note rbind requires field names to be consistent for every new thing that you add.

  saveRDS(pge_gas, "pge_elec.rds")
  }
}

#---------------------------------------------------------------------

# Gas Consumption 2021
year <- 2021
quarters <- 1:2
type <- "Gas"

for(quarter in quarters) {
  
  filename <- 
    paste0(
      "pge/PGE_",
      year,
      "_Q",
      quarter,
      "_",
      type,
      "UsageByZip.csv"
    )

  print(filename)
  
  temp <- read_csv(filename)
  
  pge_gas <- rbind(pge_gas,temp)
  # Note rbind requires field names to be consistent for every new thing that you add.

  saveRDS(pge_gas, "pge_gas.rds")
}

#---------------------------------------------------------------------

# filter gas data with customerclass: residential and commercial
pge_gas_filter <- 
  filter(
    pge_gas,
    CUSTOMERCLASS %in% 
      c(
        "Gas- Residential",
        "Gas- Commercial"
      )
  )

#---------------------------------------------------------------------

# Convertion
pge_gas_filter<-within(pge_gas_filter,kBTUs<-TOTALTHM*100)
pge_gas_filter2 <- pge_gas_filter[,-c(7,8)]

#---------------------------------------------------------------------

pge_final<-rbind(pge_elec_filter2,pge_gas_filter2)

#---------------------------------------------------------------------

pge_mutate<-
  mutate(pge_final,
      DATE = 
        paste(
          YEAR,
          MONTH, 
          "01",
          sep="-"
        ) %>% as.Date()
  )

#---------------------------------------------------------------------

# Partition data into residential and commercial sections
pge_commercial<-filter(pge_mutate,CUSTOMERCLASS%in% 
      c(
        "Elec- Commercial",
        "Gas- Commercial"
      ))
pge_residential<- filter(pge_mutate,CUSTOMERCLASS%in% 
      c(
        "Elec- Residential",
        "Gas- Residential"
      ))

#---------------------------------------------------------------------

library(plotly)

#---------------------------------------------------------------------

pge_chart_residential <-
  pge_residential %>% 
  ggplot() +
  geom_bar(
    aes(
      x = DATE %>% factor(),
      y = kBTUs,
      fill = CUSTOMERCLASS
    ),
    stat = "identity",
    position = "stack"
  ) +
  labs(
    x = "Months",
    y = "kBTUs",
    title = "PGE 2017M1 - 2021M6 Monthly Residential Electricity and Gas Consumption",
    fill = "Consumption Category"
  ) +
  scale_x_discrete(guide = guide_axis(check.overlap = TRUE))
pge_chart_residential


```


```{r}

pge_chart_commercial <-
  pge_commercial %>% 
  ggplot() +
  geom_bar(
    aes(
      x = DATE %>% factor(),
      y = kBTUs,
      fill = CUSTOMERCLASS
    ),
    stat = "identity",
    position = "stack"
  ) +
  labs(
    x = "Months",
    y = "kBTUs",
    title = "PGE 2017M1 - 2021M6 Monthly Commercial Electricity and Gas Consumption",
    fill = "Consumption Category"
  ) +
  scale_x_discrete(guide = guide_axis(check.overlap = TRUE))
pge_chart_commercial

```
